package com.lin.bulter.repository.mysql.entity;

public class PornVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_2.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_2.video
     *
     * @mbg.generated
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_2.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_2.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_2.id
     *
     * @return the value of t_video_2.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_2.id
     *
     * @param id the value for t_video_2.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_2.video
     *
     * @return the value of t_video_2.video
     * @mbg.generated
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_2.video
     *
     * @param video the value for t_video_2.video
     * @mbg.generated
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_2.title
     *
     * @return the value of t_video_2.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_2.title
     *
     * @param title the value for t_video_2.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_2.img
     *
     * @return the value of t_video_2.img
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_2.img
     *
     * @param img the value for t_video_2.img
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}