spring:
  profiles:
    active: db,redis,dev
  application:
    name: bulter-blog-main
  servlet:
    ############### 文件上传 ###############
    multipart:
      # 单个文件的最大值
      max-request-size: 10MB
      # 上传文件总的最大值
      max-file-size: 10MB

# 服务器配置
server:
  port: 8082

encryptSalt: F12839WhsnnEV$#23b

generate:
  oldGitTemplateBasePath: e:/github-template
  newProjectCodeBasePath: e:/workspace-tmp
  zipBasePath: E:/tools/nginx-1.13.3/html/download
  downDomain: https://www.wcler.cn


