spring:
  profiles:
    active: db,redis
  application:
    name: bulter-blog-main

# 服务器配置
server:
  port: 8082

generate:
  oldGitTemplateBasePath: e:/github-template
  oldGitTemplateBasePath2: e:/github-template2
  newProjectCodeBasePath: e:/workspace-tmp
  zipBasePath: E:/tools/nginx-1.13.3/html/download
  downDomain: http://www.wenself.com


